source /etc/bashrc

# some more ls aliases
alias ll='ls -alFG'
alias ls='ls -G'
alias la='ls -AG'
alias l='ls -CFG'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias git-log='git log --decorate'

